### ISSUE TITLE
CASIA-WebFace-112X96.txt

### ISSUE THREAD

**Issue by kingofkill** [MuggleWang/CosFace_pytorch#10]
where can i find this file "CASIA-WebFace-112X96.txt" or how did you get it?

**Comment by MuggleWang** [comment]
You should follow this process https://github.com/wy1iu/sphereface#part-1-preprocessing

**Comment by kingofkill** [comment]
Thank you , i have already got it.Another question: While running the code “train .sh”,my computer always have a error(“Runtime Error: CUDA error :out of memory ”).I have even put the “batch_size” to 64.The error is still have.Can you help me how to deal with it?          



            
            
                
                    
                            
                                
                            
                            
                                934617013
                            
                    
                        
                            
                                    邮箱：934617013@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 03/18/2019 16:26, Muggle Wang wrote: You should follow this process https://github.com/wy1iu/sphereface#part-1-preprocessing

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MuggleWang/CosFace_pytorch","title":"MuggleWang/CosFace_pytorch","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MuggleWang/CosFace_pytorch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MuggleWang in #10: You should follow this process https://github.com/wy1iu/sphereface#part-1-preprocessing"}],"action":{"name":"View Issue","url":"https://github.com/MuggleWang/CosFace_pytorch/issues/10#issuecomment-473813712"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MuggleWang/CosFace_pytorch/issues/10#issuecomment-473813712",
"url": "https://github.com/MuggleWang/CosFace_pytorch/issues/10#issuecomment-473813712",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MuggleWang** [comment]
./train.sh 0,1,2,3

**Comment by kingofkill** [comment]
I have tried it.It doesn’t work 



            
            
                
                    
                            
                                
                            
                            
                                934617013
                            
                    
                        
                            
                                    邮箱：934617013@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 03/18/2019 16:39, Muggle Wang wrote: ./train.sh 0,1,2,3

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MuggleWang/CosFace_pytorch","title":"MuggleWang/CosFace_pytorch","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MuggleWang/CosFace_pytorch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MuggleWang in #10: ./train.sh 0,1,2,3"}],"action":{"name":"View Issue","url":"https://github.com/MuggleWang/CosFace_pytorch/issues/10#issuecomment-473817423"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MuggleWang/CosFace_pytorch/issues/10#issuecomment-473817423",
"url": "https://github.com/MuggleWang/CosFace_pytorch/issues/10#issuecomment-473817423",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MuggleWang** [comment]
1. GPU on your computer or not?
2. run 'nvidia-smi'
3. What does 'args.cuda' return?
