### ISSUE TITLE
CASIA-WebFace and LFW

### ISSUE THREAD

**Issue by abnera** [MuggleWang/CosFace_pytorch#6]
Do you happend to have Casia-Webface and LFW dataset already preprocess, used for this experiments and share a link to download? Casia-Webface is hard to find. Will mean a lot if you can provide the datasets preprocess if not too much trouble. 

Regards.

**Comment by MuggleWang** [comment]
https://github.com/deepinsight/insightface/wiki/Dataset-Zoo

**Comment by abnera** [comment]
Thanks, I already got my own datasets using their tensorflow mtcnn directly. One thing I do want to mention is that there is only 3 overlap classes removed between casia and lfw when there are a total of 16 overlap classes between those two datasets, so the results in insightface and your repo are a bit bias. But still thanks, you have been of great help.
