### ISSUE TITLE
Question about the implementation of AngleLinear

### ISSUE THREAD

**Issue by wujiyang** [MuggleWang/CosFace_pytorch#8]
In the forward function, why mulitiply the norm of feature after output ?
`output = (one_hot * (phi_theta - cos_theta) / (1 + self.lamb)) + cos_theta   
 output *= NormOfFeature.view(-1, 1)
`

**Comment by MuggleWang** [comment]
In sphereface, author doesn't normalize the feature

**Comment by wujiyang** [comment]
> In sphereface, author doesn't normalize the feature

Thank you very much, I got it.
